### ISSUE TITLE
LeanとDevOpsの科学

### ISSUE THREAD

**Issue by kimromi** [kimromi/scraps#1]
## 事前インプット

- [『LeanとDevOpsの科学』まとめ](https://qiita.com/takeshi_nozawa/items/c115379fafeb263ed807)
- [texta.fm - 5. Accelerate](https://anchor.fm/textafm/episodes/5--Accelerate-ethnjo)

**Comment by kimromi** [comment]
## 1章

1shou

**Comment by kimromi** [comment]
## test

test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
test

**Comment by kimromi-test** [comment]
tset

**Comment by kimromi-test** [comment]
test

**Comment by kimromi** [comment]
test

**Comment by kimromi** [comment]
test

**Comment by kimromi** [comment]
# 第1部

## 1章 業務を加速させるということ

成熟度ではなくケイパビリティ(組織やグループとして保持する機能や能力)を見ていこうぜ、という話。変化に対する継続的改善、結果をベースにする、DevOpsが重要、あたりがキーワードかな。

**Comment by kimromi** [comment]
## 第3章 組織文化のモデル化と測定、改善の方法

ちょっと内容が難しかった。要は個々よりもチームが大事であり、チームや組織の文化がパフォーマンスに影響する。そして継続的デリバリやリーンマネジメントの改善が組織文化を促進させていくということを言っている（と思う）

**Comment by kimromi** [comment]
## 第4章 技術的プラクティス - 継続的デリバリの基本原則と効果

この本の肝になる継続的デリバリの話。

> 「継続的デリバリ」とは、機能の追加、構成の変更、バグの修正、各種試行など、さまざまな変更を、安全かつ迅速かつ持続可能な形で本番環境に組み込んだりユーザーに提供したりする作業を促進する一種のケイパビリティから成る手法である。

### 基本原則

- 「品質」の概念を生産工程の最初から組み込んでいく
- 作業はバッチ処理で進める
- 反復作業はコンピュータに任せて人間は問題解決に当たる
- 徹底した改善努力を継続的に行う
- 全員が責任を担う

### 継続的デリバリの促進要因

- バージョン管理
- デプロイメントの自動化
- 継続的インテグレーション
- トランクベースの開発
- テストの自動化
- テストデータの管理
- 情報セキュリティのシフトレフト
- 疎結合アーキテクチャ
- 権限を持つチーム
- モニタリング
- プロアクティブ（予防的な通知）

### 継続的デリバリの実践度高いと

- 組織への帰属意識が強い
- Four Keys で測定したデリバリのパフォーマンスレベルが高い
- 変更失敗率が低い
- パフォーマン志向で創造的な文化が浸透している

品質も上がったり、メンバーの作業割合も新たな作業に当てる時間が増えたりする。継続的デリバリの改善は正義！

**Comment by kimromi** [comment]
## 第5章 アーキテクチャのポイント

デプロイ容易性（アプリケーションを依存する他のアプリケーションやサービスからは独立した形でデプロイまたはリリースできる）、テスト容易性（テストの大半を統合環境を必要とせずに実施できる）よりも疎結合アーキテクチャが継続的デリバリの最強の促進要因になっている。これがマイクロサービスアーキテクチャを目指していく要因か〜。

**Comment by kimromi** [comment]
## 第6章 デリバリライフサイクルに情報セキュリティを組み込む

開発から運用までのライフサイクル全体に情報セキュリティが組み込んで行こうという話。DevSecOps と近いものかな？（よく知らないけど）

**Comment by kimromi** [comment]
## 第7章 ソフトウェア管理のプラクティス

リーンマネジメントが組織文化の促進、デリバリパフォーマンスの向上、バーンアウトの軽減に効果があるよという話。

### リーンマネジメント

- WIP制限
- 可視化
- ワークフローの可視化
- 負担の軽い変更承認プロセス

ちょっとマネジメント系の話になってきた？

**Comment by kimromi** [comment]
## 第8章 製品開発のプラクティス

7章とあんまり変わらないような話。

**Comment by kimromi** [comment]
## 第9章 作業を持続可能にする - デプロイ負荷とバーンアウトの軽減

バーンアウトはプロジェクト終わった時のただの燃え尽きではなくて、心身や感情面での極度の疲労を指すということで結構重大なやつだった。

バーンアウトを起こさない対処法としては

- 組織文化
- デプロイ関連の負荷
- 指導者の影響力
- DevOps導入に向けての組織レベルでの投資
- 組織のパフォーマンス

継続的デリバリの改善がひいてはバーンアウトの軽減にもつながるよという話。

**Comment by kimromi** [comment]
## 第10章 従業員の満足度、アイデンティティ、コミットメント

従業員ロイヤルティ、帰属意識、職務満足度も継続的デリバリの改善やリーンマネジメントが大きく関わるよ、という話。
短絡的なイメージとしては、継続的デリバリが改善されている → 開発しやすい → 新しいことにも取り組めたりする → 成長実感や帰属意識が高まる → ロイヤルティが上がる、みたいな感じかしら。

**Comment by kimromi** [comment]
## 第11章 変革型リーダーシップとマネジメントの役割

リーダーシップやマネジメントの話。

- ビジョン系勢力
- 心に響くコミュニケーション能力
- 知的刺激
- 支援的リーダーシップ
- 個人に対する評価

> 変革型リーダーシップと奉仕型(サーバント)リーダーシップは何を重視するかが違う。サーバントリーダーが部下自身の成長や能力に重きを置くのに対し、変革型リーダーは部下に組織との一体感をもたせ、組織の方針に従わせることに重きを置く。

管理者は他チームとつながったり、メンバーが成長できる場と機会を提供したり、情報をオープンにしたり。

リーダーや管理者って大変だよなぁ〜

**Comment by kimromi** [comment]
■ 第2部 ■ 調査・分析方法

すっとばした。

**Comment by kimromi** [comment]
## ■ 第3部 ■ 改善努力の実際

## 第16章 ハイパフォーマンスを実現するリーダーシップとマネジメント

ある企業を例にしてハイパフォーマンスを実現できている実例が紹介されている。

組織体制としては、（Spotifyでもみたっけな？）クロスファンクショナルな開発チームがありプロダクトオーナーもその中にいる。職種ごとに横断しているチャプターがあり専門技術や知識を高められるようにもなっている。例ではスクラムっぽかったけどスクラムマスターはいなかった。全体を横断するアジャイルコーチが自分たちで推進できるようにしているようには見えた。

ここまでの組織をつくるのってすごい大変そうー（棒）

**Comment by kimromi** [comment]
## 全体を通して

めちゃくちゃ勉強になった。継続的デリバリの改善やリーンマネジメントでの開発プロセスの改善が組織文化や従業員のロイヤルティにも関連があり、それがデータで相関があることがきちんと示されていることで納得感がすごかった。どこにコストを割いていけばよいかもぼんやり見えたので、開発手法や開発プロセスを考える際の辞書として活用したい本。

相関があるといってもたくさんの改善ポイントがあり、銀の弾丸は当然なくて地道に1つずつやっていかないということも改めて勉強になった。
